apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: {{ .Values.service.gatewayservicetype }}
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: {{ .Values.service.gatewayPort }}
      targetPort: 8000
      nodePort: {{ .Values.service.gatewayNodePort }}


# apiVersion: v1
# kind: Service
# metadata:
#   name: gateway-service
# spec:
#   type: NodePort
#   selector:
#     app: gateway
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
#       nodePort: 30002