apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: {{ .Values.service.ordersPort }}
      targetPort: 8000


# apiVersion: v1
# kind: Service
# metadata:
#   name: orders-service
# spec:
#   selector:
#     app: orders
#   ports:
#     - protocol: TCP
#       port: 8003
#       targetPort: 8000
#   type: {{ .Values.service.type }}