apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: users
  ports:
    - protocol: TCP
      port: {{ .Values.service.usersPort }}
      targetPort: 8000


# apiVersion: v1
# kind: Service
# metadata:
#   name: users-service
# spec:
#   selector:
#     app: users
#   ports:
#     - protocol: TCP
#       port: 8002
#       targetPort: 8000
#   type: {{ .Values.service.type }}